### PR TITLE
Global sample rate

### PR DESCRIPTION
**Pull request by RijulB**
Add optional global sample rate. Metric sample rate is honored if both global and metric sample rate are specified.

### CODE REVIEW

**Comment by bdeitte** [comment]
hi @RijulB I tend to get to merging things in on this repo on the day they are submitted, but a heads up that I don't think I will get to this tonight.  It will be sometime very soon though, and thanks for the work here.

**Comment by RijulB** [comment]
Hi @bdeitte Please merge soon. Waiting to implement in a project :)

**Comment by bdeitte** [comment]
@RijulB Emergency issue for work last night!  Top of my list to do tonight, promise.  :)

**Comment by bdeitte** [comment]
Looks good to me.  It should be in the README too, but I can do that myself after merging, and then I'll mark a new version.

**Pull request merged**
