### PR TITLE
Update to the latest mocha version to get rid of a security warning.

### PR DESCRIPTION
**Pull request by tomruggs**

### CODE REVIEW

**Comment by tomruggs** [comment]
What are your thoughts wrt Node 6 (EOL already happened) and Node 8 (EOL 2019-12-31)?

**Comment by bdeitte** [comment]
Hey @tomruggs I was going to ask why the question about Node 6, and then I see the tests!  I'm good with removing, just would want to make a major version off of it.  If you remove from the travis file and update the note in the README, that should do it.

**Comment by tomruggs** [comment]
Sorry, this fell off my radar for a while.  Node 6 has been removed and all is well.

**Comment by bdeitte** [comment]
@Tomruggs Apologies not accepted.  :P  

(Yes I know Tom, for anyone reading this and confused.)

Could you update README.md as well, says it supports 6.x?  And then I'll wait for https://github.com/brightcove/hot-shots/pull/153/files to get through, so that can have a patch version, and then put this in a new major version given the version bump.  Thanks!

**Comment by tomruggs** [comment]
Done.  And I updated nyc, which also had a bunch of vulnerabilities.  I ran the coverage script locally and all is still well despite the major version change.

**Comment by bdeitte** [comment]
Awesome thanks!  Not getting to this tonight I'm realizing but I will soon.

**Comment by tomruggs** [comment]
🎉

**Pull request merged**
